# SpaceVim init.toml
#
# Because you aren't alpha enough to mess with the VimScript.
#

[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "OceanicNext"
  colorscheme_bg = "dark"
  enable_guicolors = true
  # Status line
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  enable_statusline_mode = true
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  filemanager = "nerdtree"
  autocomplete_method = "coc"
  # Bootstrap lifecycle functions
  bootstrap_before = "user_conf#before"
  bootstrap_after = "user_conf#after"

[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = false

[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behaviour = "nil"
  auto-completion-tab-key-behaviour = "complete"

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

[[layers]]
  name = "tmux"

[[custom_plugins]]
  repo = "vim-denops/denops.vim"
  merged = false

[[custom_plugins]]
  repo = "Shougo/ddc.vim"
  merged = false

[[custom_plugins]]
  repo = "Shougo/vimproc.vim"
  merged = false
  build = "make"

[[custom_plugins]]
 repo = "bfontaine/Brewfile.vim"
 merged = false

[[custom_plugins]]
  repo = "ryanoasis/vim-devicons"
  merged = false

[[custom_plugins]]
  repo = "lambdalisue/guise.vim"
  merged = false

[[layers]]
  name="lang#rust"

[[layers]]
  name = "lang#haskell"

[[layers]]
  name = "format"
  format_on_save = true

[[layers]]
 name = "denite"

[[layers]]
 name = "lang#python"

