#!/usr/bin/env zsh

function homebrew-install() {
  if ! type "brew" > /dev/null; then
    echo "Homebrew is not installed. Installing it now..."
    /bin/bash -c "$(curl -fssl https://raw.githubusercontent.com/homebrew/install/head/install.sh)"
  else
    echo "Homebrew is already installed!"
  fi
}

homebrew-install

