#!/usr/bin/env zsh

function homebrew-install() {
  if (( $+commands[brew] )); then
    echo "Homebrew is already installed!"
  else
    echo "Homebrew is not installed. Installing it now..."
    /bin/bash -c "$(curl -fssl https://raw.githubusercontent.com/homebrew/install/head/install.sh)"
  fi
}

homebrew-install

