# .zprofile
#
# This dotfile is ran sourced .zshrc and .zlogin in both interactvive and non-
# interactive modes. It should contain the following
#
# - Environment variables that don't need to be updated often that are not
#   machine-specific
# - User-defined functions intended for use in both interactive and non-
#   interactive modes.
#
# Machine-specific environment variables should be defined in ~/.zprofile.local
# and $PATH should be defined in zshenv.
#

# Machine-specific
source $HOME/.zprofile.local

# Variables

## Directories
export GITHUB="$HOME/Documents/GitHub"
export DOTFILES="$GITHUB/dotfiles"
export ZSH_CUSTOM="$HOME/.config/ohmyzsh"
export COMP_CUSTOM="$ZSH_CUSTOM/plugins/user-completions/src"
export XDG_CONFIG_HOME="$HOME/.config"
export GNUPG_HOME="$XDG_CONFIG_HOME/gnupg"
export NVM_DIR="$XDG_CONFIG_HOME/nvm"
export NVM_HOMEBREW=$(brew --prefix nvm)

## Configs
export ZINFO_DEFAULTS="cwd-path-absolute git-overview git-last-commit date-time user platform node-v uptime"
export ZINFO_NERDFONTS=1
export GPG_TTY=$(tty)

# Functions

## GHUB command
function ghub() {
	open "https://ghub.io/$1"
}

