# .zshrc
#
# This dotfile configures zsh for interactive use. It should contain the following
#
# - Aliases
# - Oh-my-zsh setup and plugins
# - Completions
# - Prompts
# - Shell integrations
#

# Instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Aliases
alias vtop="vtop --theme monokai"
alias tree="tree --filelimit 32"
alias clr="clear && printf '\e[3J'"
alias getip="ipconfig getifaddr en1"
alias vi=nvim
alias vim=nvim
alias hstack=stack
alias machconf="vi ~/.zprofile.local"

# Oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
  git
  nvm
  osx
  gpg-agent
  poetry
  zsh-completions
  user-completions
  zsh-syntax-highlighting # must be last
)

source $ZSH/oh-my-zsh.sh

# Completions
rm -f ~/.zcompdump; compinit -i

## pyenv completions
eval "$(pyenv init -)"

# Shell Integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Functions

## Colour map
colormap() {
  for i in {0..255}
  do
    print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'};
  done
}

# Prompt
source ~/.config/p10k/conf.zsh
