# .zshrc
#
# This dotfile configures zsh for interactive use. It should contain the following
#
# - Aliases
# - Oh-my-zsh setup and plugins
# - Completions
# - Prompts
# - Shell integrations
# - Functions inended for interactive use.
#

# Aliases
alias vtop="vtop --theme monokai"
alias tree="tree --filelimit 32"
alias clr="clear && printf '\e[3J'"
alias getip="ipconfig getifaddr en1"
alias vi=nvim
alias vim=nvim
alias hstack=stack
alias machconf="vi ~/.zprofile.local"

# Oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="" # Using pure instead
plugins=(
  git
  nvm
  osx
  gpg-agent
  poetry
  zsh-syntax-highlighting # must be last
)

source $ZSH/oh-my-zsh.sh

# Completions
fpath=(/usr/local/share/zsh-completions $fpath)

rm -f ~/.zcompdump; compinit -i

## pyenv completions
eval "$(pyenv init -)"

# Shell Integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Pure theme
autoload -U promptinit; promptinit
prompt pure

